---
---

<center><h1>📍 📍 Assignment: Sorting and Aggregating Data 📍 📍</h1></center>

---

#### `READ THE DATASET`

---

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('dataset/time_series.csv')

In [3]:
data.head()

   ID          Datetime  Count
0   0  25-08-2012 00:00      8
1   1  25-08-2012 01:00      2
2   2  25-08-2012 02:00      6
3   3  25-08-2012 03:00      2
4   4  25-08-2012 04:00      2

In [4]:
data.dtypes

ID           int64
Datetime    object
Count        int64
dtype: object

#### `Convert the Datetime column to pandas datetime object`

---

In [5]:
# WRITE YOUR CODE HERE
timedata = pd.to_datetime(data.Datetime, format='%d-%m-%Y %H:%M')
timedata.head()

0   2012-08-25 00:00:00
1   2012-08-25 01:00:00
2   2012-08-25 02:00:00
3   2012-08-25 03:00:00
4   2012-08-25 04:00:00
Name: Datetime, dtype: datetime64[ns]

---

####  `Create the following features using the Datetime feature`

- day of month
- month
- day of year
- hour

---

In [6]:
# WRITE YOUR CODE HERE
day_of_month = timedata.dt.day
month = timedata.dt.month
day_of_year = timedata.dt.dayofyear
year = timedata.dt.year

---

#### `Consider the following dataframe`

---

In [7]:
sample_df = pd.DataFrame({
    'id'   :  [1, 2, 3, 4, 5],
    'name' :  [ 'Akash', 'Akansha', 'Naman', 'Pulkit', 'Anand'],
    'marks':  [ 22, 23, 43, 41, 12]
})
sample_df

   id     name  marks
0   1    Akash     22
1   2  Akansha     23
2   3    Naman     43
3   4   Pulkit     41
4   5    Anand     12

#### Sort the  dataframe by `marks` column in descending order

---

In [8]:
# WRITE YOUR CODE HERE
marks = sample_df.sort_values(by='marks', ascending=False)
marks

   id     name  marks
2   3    Naman     43
3   4   Pulkit     41
1   2  Akansha     23
0   1    Akash     22
4   5    Anand     12

#### Consider another dataframe city
---

In [9]:
city = pd.DataFrame({
    'name' : ['Akash', 'Akansha', 'Pulkit', 'Anand', 'Naman'],
    'city' : ['Delhi', 'Gurugram', 'Gurugram', 'Delhi', 'Noida']
})
city

      name      city
0    Akash     Delhi
1  Akansha  Gurugram
2   Pulkit  Gurugram
3    Anand     Delhi
4    Naman     Noida

***Use the dataframe `sample_df` and `city` and find out the marks of students who live in Gurugram.***

---

In [10]:
### Write your code here
city.merge(sample_df, how='left', on='name')

      name      city  id  marks
0    Akash     Delhi   1     22
1  Akansha  Gurugram   2     23
2   Pulkit  Gurugram   4     41
3    Anand     Delhi   5     12
4    Naman     Noida   3     43

#### `READ THE BIG MART SALES DATA`

---

In [11]:
big_mart_data = pd.read_csv('dataset/big_mart_sales.csv')

In [12]:
big_mart_data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

#### Find out the number of unique `Item_Type` in each of the `Outlet_Identifier`

---

In [13]:
# WRITE YOUR CODE HERE
big_mart_data.Item_Type.unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

#### Find out the average `Item_Outlet_Sales` for each category of `Outlet_Size`

---

In [14]:
# WRITE YOUR CODE HERE
big_mart_data.groupby('Outlet_Size')['Item_Outlet_Sales'].mean()

Outlet_Size
High      2298.995256
Medium    2681.603542
Small     1912.149161
Name: Item_Outlet_Sales, dtype: float64

#### Select only the categorical variables from the dataframe and use `get_dummies` function to convert those into the numerical ones. 

---

In [15]:
# WRITE YOUR CODE HERE
big_mart_cat = big_mart_data.select_dtypes(include='object')
big_mart_cat

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDA15,Low Fat,Dairy,OUT049,Medium,Tier 1,Supermarket Type1
1,DRC01,Regular,Soft Drinks,OUT018,Medium,Tier 3,Supermarket Type2
2,FDN15,Low Fat,Meat,OUT049,Medium,Tier 1,Supermarket Type1
3,FDX07,Regular,Fruits and Vegetables,OUT010,NaN,Tier 3,Grocery Store
4,NCD19,Low Fat,Household,OUT013,High,Tier 3,Supermarket Type1
...,...,...,...,...,...,...,...
8518,FDF22,Low Fat,Snack Foods,OUT013,High,Tier 3,Supermarket Type1
8519,FDS36,Regular,Baking Goods,OUT045,NaN,Tier 2,Supermarket Type1
8520,NCJ29,Low Fat,Health and Hygiene,OUT035,Small,Tier 2,Supermarket Type1
8521,FDN46,Regular,Snack Foods,OUT018,Medium,Tier 3,Supermarket Type2
8522,DRG01,Low Fat,Soft Drinks,OUT046,Small,Tier 1,Supermarket Type1

In [16]:
pd.get_dummies(big_mart_cat)

,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,Item_Identifier_DRB24,Item_Identifier_DRB25,Item_Identifier_DRB48,Item_Identifier_DRC01,Item_Identifier_DRC12,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8519,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8520,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8521,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8522,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0